### ISSUE TITLE
[v9.17.0.300] [workaround found] ErrorException: Warning: PDOStatement::bindParam(): Argument #2 ($var) must be passed by reference, value given

### ISSUE THREAD

**Issue by ruudk** [newrelic/newrelic-php-agent#143]
## Description

I just deployed the latest agent on PHP 8.0.3 and am getting this exception that I cannot explain: 
```
ErrorException: Warning: PDOStatement::bindParam(): Argument #2 ($var) must be passed by reference, value given
#16 /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(112): Doctrine\DBAL\Driver\PDOStatement::execute
#15 /vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1292): Doctrine\DBAL\Connection::executeQuery
#14 /vendor/doctrine/orm/lib/Doctrine/ORM/Query/Exec/SingleSelectExecutor.php(44): Doctrine\ORM\Query\Exec\SingleSelectExecutor::execute
#13 /vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(325): Doctrine\ORM\Query::_doExecute
#12 /vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1073): Doctrine\ORM\AbstractQuery::executeIgnoreQueryCache
#11 /vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(1027): Doctrine\ORM\AbstractQuery::execute
#10 /vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(791): Doctrine\ORM\AbstractQuery::getResult
```

My first thought was that this is related to Doctrine DBAL/ORM but then I searched for `bindParam` in the agent code and found:
https://github.com/newrelic/newrelic-php-agent/blob/adbdca64f20e999443d9aee7ff5d9596b32f976d/agent/php_pdo.c#L110-L123

Could it be related to this?

The Doctrine code passes it correctly via reference. 

## Your Environment

Ubuntu PHP 8.0.3

## Additional context

I'm using the latest Doctrine DBAL/ORM:
```
composer show | grep "doctrine/"
broadway/event-store-dbal               0.5.0              Event store implementation using doctrine/dbal
doctrine/annotations                    1.12.1             Docblock Annotations Parser
doctrine/cache                          1.10.2             PHP Doctrine Cache library is a popular cache implementation th...
doctrine/collections                    1.6.7              PHP Doctrine Collections library that adds additional functiona...
doctrine/common                         3.1.2              PHP Doctrine Common project is a library that provides addition...
doctrine/data-fixtures                  1.5.0              Data Fixtures for all Doctrine Object Managers
doctrine/dbal                           2.13.1             Powerful PHP database abstraction layer (DBAL) with many featur...
doctrine/deprecations                   v0.5.3             A small layer on top of trigger_error(E_USER_DEPRECATED) or PSR...
doctrine/doctrine-bundle                2.3.1              Symfony DoctrineBundle
doctrine/doctrine-fixtures-bundle       3.4.0              Symfony DoctrineFixturesBundle
doctrine/doctrine-migrations-bundle     3.1.1              Symfony DoctrineMigrationsBundle
doctrine/event-manager                  1.1.1              The Doctrine Event Manager is a simple PHP event system that wa...
doctrine/inflector                      2.0.3              PHP Doctrine Inflector is a small library that can perform stri...
doctrine/instantiator                   1.4.0              A small, lightweight utility to instantiate objects in PHP with...
doctrine/lexer                          1.2.1              PHP Doctrine Lexer parser library that can be used in Top-Down,...
doctrine/migrations                     3.1.1              PHP Doctrine Migrations project offer additional functionality ...
doctrine/orm                            2.8.4              Object-Relational-Mapper for PHP
doctrine/persistence                    2.1.0              The Doctrine Persistence project is a set of shared interfaces ...
doctrine/sql-formatter                  1.1.1              a PHP SQL highlighting library
```

**Comment by ruudk** [comment]
If you set `newrelic.transaction_tracer.explain_enabled = false` the error goes away. That proofs that the referenced code in the OP is the cause of this.

**Comment by joshuabenuck** [comment]
@ruudk Thanks for the detailed issue report and for the information on the workaround! It really helps narrow down where the problem may be. We are working on reproducing this locally.

**Comment by joshuabenuck** [comment]
I was able to reproduce the problem. I have a work in progress PR exploring the best way to fix this as it touches on a PHP 8 API change that impacts other parts of the code. What we do here will establish the pattern we need to follow in future similar scenarios. My first attempt looks to have been too general so it will need to be reworked.

**Comment by joshuabenuck** [comment]
The revised fix (with automated test) has been merged. It will be in the next release.

**Comment by kneitinger** [comment]
Hi all,

We just put out [a patch release (9.17.1) ](https://github.com/newrelic/newrelic-php-agent/releases/tag/v9.17.1.301) that addresses this issue!  We'll leave this issue open for a few days to verify that this solution is working well for folks, so please feel free to leave any feedback about your experience!  Thanks!

**Comment by ruudk** [comment]
Deployed 9.17.1.301 to production and enabled the Explain Tracer again. It works 🎉  Thanks.
