### ISSUE TITLE
Guzzle 6 Middleware pushed multiple times, reaching max recursion

### ISSUE THREAD

**Issue by Starfox64** [newrelic/newrelic-php-agent#48]
## Description

I am using `Google_Client` with `Google_Service_MyBusiness` and my cron jobs are failing since adding the PHP agent because it's Guzzle 6 middleware ends up being duplicated multiple times as I make requests to the Google APIs, which causes hundreds of instances of `newrelic\Guzzle6\middleware` to be present in Guzzle's `HandlerStack`, resulting in my code reaching the max recursion limit set in XDebug.

## Steps to Reproduce

Example with the books API (happens with any Google API)
```php
$client = new \Google_Client();
$client->setApplicationName("Client_Library_Examples");
$client->setDeveloperKey("YOUR_API_KEY");

$service = new \Google_Service_Books($client);
$results = $service->volumes->listVolumes('Henry David Thoreau', array('filter' => 'free-ebooks'));
$results = $service->volumes->listVolumes('Henry David Thoreau', array('filter' => 'free-ebooks'));
$results = $service->volumes->listVolumes('Henry David Thoreau', array('filter' => 'free-ebooks'));

foreach ($results->getItems() as $item) {
	echo $item['volumeInfo']['title'], "<br /> \n";
}

var_dump($client->getHttpClient()->getConfig('handler'));
```

## Expected Behavior

The middleware is added once and only once to the guzzle HandlerStack.

## Relevant Logs / Console output

Output from the above example:
```
array (size=9)
      0 => 
        array (size=2)
          0 => 
            object(Closure)[307]
              ...
          1 => string 'http_errors' (length=11)
      1 => 
        array (size=2)
          0 => 
            object(Closure)[308]
              ...
          1 => string 'allow_redirects' (length=15)
      2 => 
        array (size=2)
          0 => 
            object(Closure)[309]
              ...
          1 => string 'cookies' (length=7)
      3 => 
        array (size=2)
          0 => 
            object(Closure)[310]
              ...
          1 => string 'prepare_body' (length=12)
      4 => 
        array (size=2)
          0 => string 'newrelic\Guzzle6\middleware' (length=27)
          1 => string '' (length=0)
      5 => 
        array (size=2)
          0 => string 'newrelic\Guzzle6\middleware' (length=27)
          1 => string '' (length=0)
      6 => 
        array (size=2)
          0 => string 'newrelic\Guzzle6\middleware' (length=27)
          1 => string '' (length=0)
      7 => 
        array (size=2)
          0 => 
            object(Google\Auth\Middleware\SimpleMiddleware)[420]
              ...
          1 => string 'google_auth' (length=11)
      8 => 
        array (size=2)
          0 => string 'newrelic\Guzzle6\middleware' (length=27)
          1 => string '' (length=0)
```

Error occurring in production:
```
Error: Xdebug has detected a possible infinite loop, and aborted your script with a stack depth of '512' frames
#249 /libs/vendor/guzzlehttp/psr7/src/MessageTrait.php(189): is_scalar
#248 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#247 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#246 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#245 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#244 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#243 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#242 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#241 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
...
...
...
#32 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#31 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#30 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#29 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#28 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#27 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#26 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#25 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#24 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#23 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#22 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#21 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#20 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#19 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#18 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#17 newrelic/Guzzle6(1): newrelic\Guzzle6\{closure}
#16 /libs/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\PrepareBodyMiddleware::__invoke
#15 /libs/vendor/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\Middleware::GuzzleHttp\{closure}
#14 /libs/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\RedirectMiddleware::__invoke
#13 /libs/vendor/guzzlehttp/guzzle/src/Middleware.php(57): GuzzleHttp\Middleware::GuzzleHttp\{closure}
#12 /libs/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\HandlerStack::__invoke
#11 /libs/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\Client::transfer
#10 /libs/vendor/guzzlehttp/guzzle/src/Client.php(98): GuzzleHttp\Client::sendAsync
#9 /libs/vendor/guzzlehttp/guzzle/src/Client.php(106): GuzzleHttp\Client::send
#8 /libs/vendor/google/auth/src/HttpHandler/Guzzle6HttpHandler.php(34): Google\Auth\HttpHandler\Guzzle6HttpHandler::__invoke
#7 /libs/vendor/google/apiclient/src/Google/Http/REST.php(74): Google_Http_REST::doExecute
#6 /libs/vendor/google/apiclient/src/Google/Task/Runner.php(176): Google_Task_Runner::run
#5 /libs/vendor/google/apiclient/src/Google/Http/REST.php(58): Google_Http_REST::execute
#4 /libs/vendor/google/apiclient/src/Google/Client.php(842): Google_Client::execute
#3 /libs/vendor/google/apiclient/src/Google/Service/Resource.php(232): Google_Service_Resource::call
#2 /libs/classmaps/GoogleMyBusiness.php(1727): Google_Service_MyBusiness_AccountsLocations_Resource::patch
#1 /jobs/AgencySync.php(124): CronJob\AgencySync::execute
#0 /scripts/Cron.php(39): null
```

## Your Environment

PHP Version: 7.3.25
Agent Version: 9.14.0.290

## Additional context

N/A

**Comment by joshuabenuck** [comment]
@Starfox64 Thank you for the bug report and the reproduction! I've managed to track down what is happening.

The functions in `Google\AuthHandler\Guzzle6AuthHandler` register the `google_auth` middleware in the Guzzle Client config. The problem is that they do this by extracting the config, modifying it, and then [creating a new Guzzle Client](https://github.com/googleapis/google-api-php-client/blob/b39ee320efbfb4096b4c4771a9b43d9d14d11746/src/AuthHandler/Guzzle6AuthHandler.php#L66).

The New Relic agent registers its middleware [whenever a new Client is created](https://github.com/newrelic/newrelic-php-agent/blob/b41aee57df47c4eb5d3c6c88e63f991f8258556c/agent/lib_guzzle6.c#L345), but doesn't guard against this scenario so it ends up reregistering every time one of `Guzzle6AuthHandler` methods are called.

If you want to avoid rebuilding the agent, a short term workaround might be to modify your copy of `google-api-php-client/src/AuthHandler/Guzzle6AuthHandler.php`. A couple of options to try are:
1. Removing the newrelic middleware registration by adding a call to `$config['handler]->remove('newrelic\\Guzzle6\\middleware');` right around where the Google code is removing its `google_auth` registration.
1. Modifying the Google code so it adds its `google_auth` middleware registration in place instead of creating a new `Client` object. (This approach assumes that there any problem with reusing an existing Guzzle Client, if there is, option # 1 would need to be used).

The fix for the agent will likely be doing something along the lines of # 1 within the agent's [middleware registration code](https://github.com/newrelic/newrelic-php-agent/blob/b41aee57df47c4eb5d3c6c88e63f991f8258556c/agent/lib_guzzle6.c#L401).

**Comment by Starfox64** [comment]
It's as I was suspecting as I was unable to reproduce it with a bare Guzzle client. For now I've just disabled instrumentation on this specific job until this eventually get's resolved.

**Comment by andrekutianski** [comment]
I have the same issue, but my page administration is broken due to this.

**Comment by ccharlton** [comment]
I see this ticket was marked closed. Since the issue with Guzzle still persists in recent versions of the PHP Agent, is there a planned solution/ticket for fixes in the NR agent?
