### ISSUE TITLE
PHP Agent Causes Fatal Errors in Guzzle Requests

### ISSUE THREAD

**Issue by omacranger** [newrelic/newrelic-php-agent#85]
## Description

After installing & enabling the NewRelic PHP Agent on an Ubuntu machine running PHP7.3, Laravel 7.x we're seeing numerous Guzzle requests fail with a `Unsupported operand types` exception. Other users have reported similar errors and there's a thread on the NewRelic forums [here](https://discuss.newrelic.com/t/php-guzzle-errors-in-php-agent-9-0/91477/15). Disabling the extension resolves the issue.

## Steps to Reproduce

Will work to further create a sample repo / test scenario.

## Relevant Logs / Console output

<details>
<summary>Sample exception here</summary>

```
[object] (Error(code: 0): Unsupported operand types at /var/www/vendor/guzzlehttp/guzzle/src/Client.php:310)
[stacktrace]
#0 /var/www/vendor/guzzlehttp/guzzle/src/Client.php(148): GuzzleHttp\\Client->prepareDefaults(Array)
#1 /var/www/vendor/guzzlehttp/guzzle/src/Client.php(182): GuzzleHttp\\Client->requestAsync('shouldReport', Array, Array)
#2 /var/www/vendor/guzzlehttp/guzzle/src/Client.php(95): GuzzleHttp\\Client->request('shouldReport', Array, Array)
#3 /var/www/vendor/guzzlehttp/guzzle/src/Client.php(62): GuzzleHttp\\Client->__call('shouldReport', Array)
#4 /var/www/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(621): GuzzleHttp\\Client->__construct(Array)
#5 /var/www/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(554): Illuminate\\Http\\Client\\PendingRequest->buildClient()
#6 /var/www/vendor/laravel/framework/src/Illuminate/Support/helpers.php(404): Illuminate\\Http\\Client\\PendingRequest->Illuminate\\Http\\Client\\{closure}(1)
#7 /var/www/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(570): retry(0, Object(Closure), 100)
#8 /var/www/vendor/laravel/framework/src/Illuminate/Http/Client/PendingRequest.php(474): Illuminate\\Http\\Client\\PendingRequest->send('POST', 'redacted', Array)
#9 /var/www/app/Jobs/ProcessorJob.php(54): Illuminate\\Http\\Client\\PendingRequest->post('redacted', Array)
#10 [internal function]: App\\Jobs\\ProcessorJob->handle()
#11 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array(Array, Array)
#12 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#14 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#15 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#16 /var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#17 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(App\\Jobs\\ProcessorJob))
#18 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\ProcessorJob))
#19 /var/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#20 /var/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(App\\Jobs\\ProcessorJob), false)
#21 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}(Object(App\\Jobs\\ProcessorJob))
#22 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(App\\Jobs\\ProcessorJob))
#23 /var/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#24 /var/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(App\\Jobs\\Or$
#25 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\RedisJob), Array)
#26 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\\Queue\\Jobs\\Job->fire()
#27 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\\Queue\\Worker->process('redis', Object(Illuminate\\Queue\\Jobs\\RedisJob), Object(Illuminate\\Queue\\WorkerOptions))
#28 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\\Queue\\Worker->runJob(Object(Illuminate\\Queue\\Jobs\\RedisJob), 'redis', Object(Illuminate\\Queue\\WorkerOptions))
#29 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon('redis', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#30 /var/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'default')
#31 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#32 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array(Array, Array)
#33 /var/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#34 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#35 /var/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#36 /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#37 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call(Array)
#38 /var/www/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#39 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\$
#40 /var/www/vendor/symfony/console/Application.php(911): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#41 /var/www/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInpu$
#42 /var/www/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleO$
#43 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Con$
#44 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Cons$
#45 /var/www/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#46 {main}
```

</details>

## Your Environment

- PHP 7.3.26 FPM
- Fresh installation of the NewRelic PHP Agent
- Laravel 7.25
- Guzzle requests were generated / called using the `Http` Laravel facade

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by joelvh** [comment]
@omacranger we ran into this with Guzzle 7.x -- the agent officially only supports up to Guzzle 6.x

We saw this inconsistently, but it seems that the `$config` property on `PendingRequest` in laravel's HTTP client would be set to `null` before a request, which caused `$this->config + $defaults` to throw that exception. We couldn't find any scenario where the value would be set to `null`, so it must be something in how NewRelic patches requests for instrumentation.

**Comment by hahuja2** [comment]
Hi! We are currently working on this issue and trying to reproduce the error. We are using different methods including traffic loading and sending large amounts of data to the server, but have been unable to reproduce the issue. If possible, could you please share a snippet of your code that causes this issue and what environment you are using (guzzle/laravel/php/os/etc). I would also like to confirm that the PHP Agent does not support Laravel 8 and Guzzle 7 currently, but is working on supporting those versions soon. Thank you!

**Comment by g4ther** [comment]
Hey @hahuja2, we've since updated our system and disabled a large part of New Relic due to the lack of support for Laravel & Guzzle, however at the time we were running on PHP 7.3, Laravel 7.22.4 and Guzzle 6.5.5. It also seemed to be related to having Predis installed and run after a Predis call.

I posted a heap more information from back in the day here: https://discuss.newrelic.com/t/php-when-to-call-getconnection/114848/8

**Comment by zanderwar** [comment]
A bit strange to only support versions of guzzle that have severe security vulnerabilities.

https://security.snyk.io/package/composer/guzzlehttp%2Fguzzle
https://github.com/guzzle/guzzle/blob/master/UPGRADING.md#60-to-70

**Comment by deviantintegral** [comment]
We are seeing this on a Drupal 9.4 site, which currently ships with Guzzle 6.5.8. We don't have a good reproduction case, as so far the error hasn't come up live for any of our team, but does show up occasionally in the New Relic errors inbox.

We were seeing this error when our site was in a pre-launch state, and it seemed like it would cause a significant error percentage. However, even with live traffic the number of errors stayed the same or possibly decreased. So, I don't think testing under load helps reproduce this.

Our environment does have redis, but using PhpRedis and not Predis.

We're erroring on line 260 at `$this->config = $config + $defaults;`.

> Noticed exception 'TypeError' with message 'Unsupported operand types: array + null' in /code/vendor/guzzlehttp/guzzle/src/Client.php:310

Somehow, `$defaults` is becoming null, which to me indicates a memory corruption issue given that value is never assigned null in Guzzle:

https://github.com/guzzle/guzzle/blob/6.5.8/src/Client.php#L225-L260

**Comment by deviantintegral** [comment]
This appears to have been fixed when our hosting provider upgraded the New Relic agent from `10.2` to `10.5.0.317 ("hydrangea" - "f21ec1ea828e")`.

**Comment by Ak-x** [comment]
Closing this per last comment. Please re-open if this issue persists.
